name: "DocFX Setup"
description: ""
inputs:
  github-token:
    description: ''
    default: ''
    
  docs-directory:
    description: ''
    default: '$PWD/docs'

  docfx-version:
    description: ''
    default: '2.66.1'

  newtonsoftjson-version:
    description: ''
    default: '13.0.1'

runs:
  using: "composite"
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Setup .NET 7
      uses: actions/setup-dotnet@master
      with:
        dotnet-version: 7.x.x

    - name: Setup BUTR GPR
      uses: actions/setup-dotnet@master
      with:
        source-url: https://nuget.pkg.github.com/BUTR/index.json
      env:
        NUGET_AUTH_TOKEN: ${{inputs.github-token}}

    - name: Generating Newtonsoft.Json xref maps
      run: >-
        dotnet run --project ${{ github.action_path }}/build/SandcastleXrefGenerator -- `
            Newtonsoft.Json ${{inputs.newtonsoftjson-version}} netstandard2.0 `
            https://www.newtonsoft.com/json/help/html/ `
            ${{inputs.docs-directory}}/xrefs/Newtonsoft.Json-xrefmap.yml
      shell: pwsh

    - name: Build DocFx.Plugin.LastModified
      run: dotnet build ${{ github.action_path }}/build/DocFx.Plugin.LastModified --configuration Release --output ${{inputs.docs-directory}}/_template/last-modified/plugins;
      shell: pwsh

    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - run: npm install
    - run: npm run build
    - run: dotnet pack -c Release /p:Version=2.60.0 -o ./drop/nuget
    - run: dotnet tool install -g --add-source ./drop/nuget docfx
