name: "DocFX Setup"
description: ""
inputs:
  github-token:
    description: ''
    default: ''
    
  docs-directory:
    description: ''
    default: '$PWD/docs'

  docfx-version:
    description: ''
    default: '2.58.4'

  newtonsoftjson-version:
    description: ''
    default: '11.0.2'

runs:
  using: "composite"
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Setup .NET Core 3.1
      uses: actions/setup-dotnet@master
      with:
        dotnet-version: 3.1.x

    - name: Setup .NET 5
      uses: actions/setup-dotnet@master
      with:
        dotnet-version: 5.0.x

    - name: Ensure NuGet Source
      uses: fabriciomurta/ensure-nuget-source@v1
      with:
        name: 'nuget.org'
        url: 'https://api.nuget.org/v3/index.json'

    - name: Setup BUTR GPR
      uses: actions/setup-dotnet@master
      with:
        source-url: https://nuget.pkg.github.com/BUTR/index.json
      env:
        NUGET_AUTH_TOKEN: ${{inputs.github-token}}
        
    - name: Setup NuGet
      uses: nuget/setup-nuget@v1
      with:
        nuget-version: 'latest'
        
    - name: Generating Newtonsoft.Json xref maps
      run: >-
        dotnet run --project ${{ github.action_path }}/build/SandcastleXrefGenerator -- `
            Newtonsoft.Json ${{inputs.newtonsoftjson-version}} netstandard2.0 `
            https://www.newtonsoft.com/json/help/html/ `
            ${{inputs.docs-directory}}/xrefs/Newtonsoft.Json-xrefmap.yml
      shell: pwsh

    - name: Build DocFx.Plugin.LastModified
      run: >-
        dotnet build ${{ github.action_path }}/build/DocFx.Plugin.LastModified --configuration Release --output ${{inputs.docs-directory}}/_template/last-modified/plugins;
      shell: pwsh

    - name: Install DocFX
      run: >-
        nuget install docfx.console -Version ${{inputs.docfx-version}} -ExcludeVersion;
      shell: pwsh
      
    - name: Global Long Path Support
      run: >-
        New-Item -Path 'HKLM:\SOFTWARE\Microsoft\.NETFramework\AppContext'
        New-ItemProperty -Path 'HKLM:\SOFTWARE\Microsoft\.NETFramework\AppContext' -Name 'Switch.System.IO.UseLegacyPathHandling' -Value 'false'
        New-ItemProperty -Path 'HKLM:\SOFTWARE\Microsoft\.NETFramework\AppContext' -Name 'Switch.System.IO.BlockLongPaths' -Value 'false'
      shell: pwsh
